[regions]
demo.livingatlas.org

[regions:vars]
local_repo_dir=~/.ala
data_dir=/data

regions_hostname=demo.livingatlas.org
regions_context_path=/regions
regions_base_url=http://demo.livingatlas.org

ala_base_url=http://demo.livingatlas.org
bie_base_url=http://demo.livingatlas.org/ala-hub
bie_service_base_url=http://demo.livingatlas.org/bie-index
biocache_base_url=http://demo.livingatlas.org/biocache-service
biocache_service_base_url=http://demo.livingatlas.org/biocache-service
spatial_base_url=http://spatial.livingatlas.org
spatial_base_url_ws=http://spatial.livingatlas.org/ws
geoserver_base_url=http://spatial.livingatlas.org/geoserver
logger_base_url=https://logger.ala.org.au
alerts_base_url=https://alerts.ala.org.au
security_cas_login_url=https://auth.ala.org.au/cas/login
biocache_records_url=http://biocache.vagrant1.ala.org.au/

auth_base_url=https://auth.ala.org.au
auth_cas_url=https://auth.ala.org.au/cas

regions=regions

webserver_nginx=true