---
# Used only for Debian/Ubuntu installation, as the -t option for apt.
nginx_default_release: ""

# Used only for Redhat installation, enables source Nginx repo.
nginx_yum_repo_enabled: true

# Use the official Nginx PPA for Ubuntu, and the version to use if so.
nginx_ppa_use: true
nginx_ppa_version: stable

# The name of the nginx package to install.
nginx_package_name: "nginx"

# Whether to include modules e.g. PAM auth, geoip, stream etc
# Note this overrides nginx_extra_conf_options initial value.
nginx_use_modules: false

nginx_conf_template: "nginx.conf.j2"
nginx_mime_template: "mime.types.j2"
nginx_vhost_template: "vhost.j2"

nginx_worker_processes: "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

nginx_error_log: "/var/log/nginx/error.log info"
nginx_access_log: "/var/log/nginx/access.log main"

# Other log formats, including the name and then the format. E.g.,
#     postdata '$request_body';
nginx_other_log_formats: []

nginx_sendfile: "on"
nginx_tcp_nopush: "on"
nginx_tcp_nodelay: "on"

nginx_keepalive_timeout: "10"
nginx_keepalive_requests: "100"
nginx_send_timeout: "10"

nginx_server_tokens: "off"

nginx_client_max_body_size: "64m"

nginx_server_names_hash_bucket_size: "64"

nginx_proxy_cache_path: ""

nginx_gzip_enabled: True
nginx_gzip_min_length: 1024
nginx_gzip_types: "text/plain application/xml application/html text/json application/json text/javascript application/javascript text/css application/css application/octet-stream"

nginx_extra_conf_options: ""
# Example extra main options, used within the main nginx's context:
#   nginx_extra_conf_options: |
#     env VARIABLE;
#     include /etc/nginx/main.d/*.conf;

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

nginx_remove_default_vhost: false
nginx_vhosts: []
# Example vhost below, showing all available options:
# - listen: "80" # default: "80"
#   server_name: "example.com" # default: N/A
#   root: "/var/www/example.com" # default: N/A
#   index: "index.html index.htm" # default: "index.html index.htm"
#   filename: "example.com.conf" # Can be used to set the filename of the vhost file.
#
#   # Properties that are only added if defined:
#   server_name_redirect: "www.example.com" # default: N/A
#   error_page: ""
#   access_log: ""
#   error_log: ""
#   extra_parameters: "" # Can be used to add extra config blocks (multiline).
#   template: "" # Can be used to override the `nginx_vhost_template` per host.
#   state: "absent" # To remove the vhost configuration.

nginx_upstreams: []
# - name: myapp1
#   strategy: "ip_hash" # "least_conn", etc.
#   keepalive: 16 # optional
#   servers: {
#     "srv1.example.com",
#     "srv2.example.com weight=3",
#     "srv3.example.com"
#   }

nginx_log_format: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for" request_time=$request_time upstream_response_time=$upstream_response_time upstream_connect_time=$upstream_connect_time upstream_header_time=$upstream_header_time upstream_cache_status=$upstream_cache_status'

# Add strings to this list containing the vhost fragment directory names to clear
nginx_vhost_fragments_to_clear: []
# Define the following and set it to true to override the warning about the nginx vhost fragments to clear directory not being specified
# If there are multiple apps being deployed to a single vhost, this must be set to True to override the warnings
# WARNING: You must also understand the issues associated with attempting to deploy multiple apps to a single vhost and when you will need to manually clear and reinstall the nginx configuration in this case
#nginx_vhost_fragments_to_clear_no_warning: False
