- include: ../../common/tasks/setfacts.yml 
  tags:
    - java

# OpenJDK-8 is needed to fulfill the default JRE role so Tomcat can be installed
# Note, oracle-java8-set-default is installed later on so it is used by default
- name: install openjdk 8 java (Debian)
  apt: pkg=openjdk-8-jdk state=present update_cache=yes
  when: ansible_os_family == "Debian" and use_oraclejava8 is defined
  tags:
    - java
  ignore_errors: yes

- name: Install add-apt-repostory
  become: yes
  apt: name=software-properties-common state=latest
  when: ansible_os_family == "Debian" and use_oraclejava8 is defined
  tags:
    - java

- name: Add Oracle Java Repository
  become: yes
  apt_repository: 
    repo: 'ppa:webupd8team/java'
    update_cache: yes
  when: ansible_os_family == "Debian" and use_oraclejava8 is defined
  tags:
    - java

- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  when: ansible_os_family == "Debian" and use_oraclejava8 is defined
  tags:
    - java

# Need to attempt to install oracle java8 before the files that we may need to patch are in location, so ignore errors for this attempt
- name: Install Oracle Java 8 (before possibly patching files)
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
  ignore_errors: yes
  when: ansible_os_family == "Debian" and use_oraclejava8 is defined
  tags:
    - java

- name: Fix Webupd8 Team failing to update and Oracle removing old download
  become: yes
  shell: >
    cd /var/lib/dpkg/info &&
    sed -i 's|JAVA_VERSION=8u181|JAVA_VERSION=8u191|' oracle-java8-installer.* &&
    sed -i 's|PARTNER_URL=http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/|PARTNER_URL=https://download.oracle.com/otn-pub/java/jdk/8u191-b12/2787e4a523244c269598db4e85c51e0c/|' oracle-java8-installer.* &&
    sed -i 's|SHA256SUM_TGZ="1845567095bfbfebd42ed0d09397939796d05456290fb20a83c476ba09f991d3"|SHA256SUM_TGZ="53c29507e2405a7ffdbba627e6d64856089b094867479edc5ede4105c1da0d65"|' oracle-java8-installer.* &&
    sed -i 's|J_DIR=jdk1.8.0_181|J_DIR=jdk1.8.0_191|' oracle-java8-installer.*
  when: ansible_os_family == "Debian" and use_oraclejava8 is defined
  tags:
    - java

- name: Install Oracle Java 8 (after possibly patching files)
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
  when: ansible_os_family == "Debian" and use_oraclejava8 is defined
  tags:
    - java
