- name: debconf (Debian)
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  when: ansible_os_family == "Debian"
  tags:
    - java

- name: debconf2 (Debian)
  shell: echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
  when: ansible_os_family == "Debian"
  tags:
    - java

- name: install software-properties-common (Debian)
  apt: pkg=software-properties-common  state=present update_cache=yes
  when: ansible_os_family == "Debian"
  tags:
    - java

- name: install python-software-properties (Debian)
  apt: pkg=python-software-properties  state=present update_cache=yes
  when: ansible_os_family == "Debian"
  tags:
    - java

- name: apt-add-repository (Debian)
  apt_repository: repo='ppa:webupd8team/java'
  when: ansible_os_family == "Debian"
  tags:
    - java

- name: install oracle 7 java (Debian)
  apt: pkg=oracle-java7-installer state=present update_cache=yes
  when: ansible_os_family == "Debian"
  tags:
    - java

- name: set oracle 7 java  (Debian)
  apt: pkg=oracle-java7-set-default
  when: ansible_os_family == "Debian"
  tags:
    - java
