# This must be explicitly enabled as most users do not require this functionality
geoip_enabled: False

# Maxmind is the company providing the geoip database that logstash uses to geolocate IP addresses and identify ASNs

# Create a MaxMind account and get a license key using the instructions at:
# https://dev.maxmind.com/geoip/geoipupdate/
#maxmind_account_id: "NNNNNNN"
#maxmind_license_key: "XYZABC"

maxmind_edition_ids: ["GeoLite2-ASN", "GeoLite2-City", "GeoLite2-Country"]

maxmind_geoip_conf: "/etc/GeoIP.conf"

maxmind_geoip_database_directory: "/usr/share/GeoIP"

