- hosts: ala-demo
  roles:
    - common
    - java
    - tomcat
    - cassandra
    - mysql
    - apache
    - nameindex
    - solr
    - logger-client
    - biocache-db
    - biocache-service
    - { role: biocache-hub, biocache_hub: generic-hub }
    - collectory-db
    - collectory
    - sandbox
    - demo-apache
    - biocache-cli
    - nameindexer    
    - logger-service
