- hosts: sandbox
  roles:
    - common
    - java
    - tomcat
    - cassandra
    - apache
    - nameindex
    - biocache-db
    - biocache-service
    - { role: biocache-hub, biocache_hub: ala-hub }
    - sandbox
    - solr    
    - sandbox-apache
    - biocache-cli
