# common variables across all roles
tomcat_java_opts: -Xmx2g -Xms2g -Xss512k -Djava.awt.headless=true
tomcat_control_port: 8005
tomcat_http: true
tomcat_http_port: 8080
tomcat_ajp: false
tomcat_ajp_port: 8009
tomcat_apr: true
tomcat_users: true
tomcat_autoDeploy: true
tomcat_bind_addr: 127.0.0.1
tomcat_umask: "0022"
tomcat_max_post_size: 2097152

# Set to a string containing the characters to relax URL encoding on.
# Search for `relaxedQueryChars` on this page for more details:
# https://tomcat.apache.org/tomcat-9.0-doc/config/http.html
tomcat_relaxed_query_chars: ""
