# assets
version: "1.3.1"
artifactId: "ala-cas"
classifier: ''
packaging: "war"
cas_war_url: "{{maven_repo_ws_url}}"

tomcat_java_opts_override: "-Xmx4g -Xms2g -XX:MaxPermSize=256m -Xss256k -XX:+UseG1GC"
