# Default variables for the mongodb-org role
# common variables across all roles
mongodb_bind_ip: 127.0.0.1
mongodb_port: 27017
dbPath: /var/lib/mongodb
mongodb_root_username: admin
mongo_cluster_enabled: False